name: Build and push to gh-pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get remote branch
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3

      - name: install dependencies
        run: |
          git reset origin/master --hard
          npm ci

      - name: build project
        run: |
          git branch
          npm run build
          cat index.html
          rm index.html
          mkdir ~/build
          cp -ar build/* ~/build/
          cd ~/
          mkdir second_repo
          cd second_repo

      - name: get remote branch 2
        uses: actions/checkout@v3

      - name: configure second repo
        run: |
          git fetch
          git checkout gh-pages
          cp -r ~/build/. ./
          ls

      - name: set credentials
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: add build folder
        run: |
          git add assets
          git add index.html

      - name: git commit
        run: |
          git commit -m "auto-deploy"

      - name: push
        run: git push origin gh-pages -f
